"""Auto-generated migration

Revision ID: 31b07ed07a1e
Revises: 8148f20aee01
Create Date: 2025-11-22 05:07:29.575776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b07ed07a1e'
down_revision: Union[str, Sequence[str], None] = '8148f20aee01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_entries', sa.Column('weather_relative_humidity_pct', sa.Float(), nullable=True))
    op.add_column('log_entries', sa.Column('weather_dew_point_f', sa.Float(), nullable=True))
    op.add_column('log_entries', sa.Column('weather_precipitation_probability_pct', sa.Float(), nullable=True))
    op.add_column('log_entries', sa.Column('weather_precipitation_amount_in', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_entries', 'weather_precipitation_amount_in')
    op.drop_column('log_entries', 'weather_precipitation_probability_pct')
    op.drop_column('log_entries', 'weather_dew_point_f')
    op.drop_column('log_entries', 'weather_relative_humidity_pct')
    # ### end Alembic commands ###
