"""Auto-generated migration

Revision ID: 8148f20aee01
Revises:
Create Date: 2025-11-21 20:50:58.841393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '8148f20aee01'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Enable pgvector extension
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('media_type', sa.Enum('AUDIO', 'VIDEO', name='mediatype'), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('is_video_source', sa.Boolean(), nullable=False),
    sa.Column('log_type', sa.Enum('PERSONAL', 'SHIP', name='logtype'), nullable=False),
    sa.Column('video_s3_key', sa.String(), nullable=True),
    sa.Column('video_local_path', sa.String(), nullable=True),
    sa.Column('audio_s3_key', sa.String(), nullable=True),
    sa.Column('audio_local_path', sa.String(), nullable=True),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'TRANSCRIBING', 'VECTORIZING', 'SUMMARIZING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('location_name', sa.String(), nullable=True),
    sa.Column('location_city', sa.String(), nullable=True),
    sa.Column('location_state', sa.String(), nullable=True),
    sa.Column('location_country', sa.String(), nullable=True),
    sa.Column('body_of_water', sa.String(), nullable=True),
    sa.Column('nearest_port', sa.String(), nullable=True),
    sa.Column('weather_air_temp_f', sa.Float(), nullable=True),
    sa.Column('weather_water_temp_f', sa.Float(), nullable=True),
    sa.Column('weather_wind_speed_kts', sa.Float(), nullable=True),
    sa.Column('weather_wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('weather_wind_gust_kts', sa.Float(), nullable=True),
    sa.Column('weather_wave_height_ft', sa.Float(), nullable=True),
    sa.Column('weather_wave_period_sec', sa.Float(), nullable=True),
    sa.Column('weather_barometric_pressure_mb', sa.Float(), nullable=True),
    sa.Column('weather_visibility_nm', sa.Float(), nullable=True),
    sa.Column('weather_conditions', sa.String(), nullable=True),
    sa.Column('weather_forecast', sa.Text(), nullable=True),
    sa.Column('weather_captured_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('setting_type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('vessel_name', sa.String(length=255), nullable=False),
    sa.Column('vessel_designation', sa.String(length=255), nullable=False),
    sa.Column('openai_model_whisper', sa.String(length=100), nullable=False),
    sa.Column('openai_model_embedding', sa.String(length=100), nullable=False),
    sa.Column('openai_model_chat', sa.String(length=100), nullable=False),
    sa.Column('media_storage_mode', sa.Enum('S3_ONLY', 'LOCAL_WITH_S3', name='mediastoragemode'), nullable=False),
    sa.Column('local_media_path', sa.String(length=500), nullable=True),
    sa.Column('max_audio_file_size', sa.Integer(), nullable=False),
    sa.Column('max_video_file_size', sa.Integer(), nullable=False),
    sa.Column('allowed_audio_formats', sa.JSON(), nullable=False),
    sa.Column('allowed_video_formats', sa.JSON(), nullable=False),
    sa.Column('default_page_size', sa.Integer(), nullable=False),
    sa.Column('max_page_size', sa.Integer(), nullable=False),
    sa.Column('enable_resilient_processing', sa.Boolean(), nullable=False),
    sa.Column('max_network_retries', sa.Integer(), nullable=False),
    sa.Column('network_retry_base_delay', sa.Integer(), nullable=False),
    sa.Column('network_retry_max_delay', sa.Integer(), nullable=False),
    sa.Column('aws_access_key_id', sa.String(length=255), nullable=True),
    sa.Column('aws_secret_access_key', sa.String(length=255), nullable=True),
    sa.Column('aws_region', sa.String(length=50), nullable=True),
    sa.Column('s3_bucket_name', sa.String(length=255), nullable=True),
    sa.Column('s3_audio_prefix', sa.String(length=100), nullable=False),
    sa.Column('s3_video_prefix', sa.String(length=100), nullable=False),
    sa.Column('s3_presigned_url_expiry', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_table('log_entries')
    # ### end Alembic commands ###

    # Drop pgvector extension
    op.execute('DROP EXTENSION IF EXISTS vector')
