"""Add init workflow fields

Adds s3_base_url and authentication/OAuth settings to user_preferences.
Adds FastAPI Users fields to users table.

Revision ID: aa817c3300c9
Revises: add_user_support
Create Date: 2025-11-22 18:50:16.740860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa817c3300c9'
down_revision: Union[str, Sequence[str], None] = 'add_user_support'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Add UserPreferences fields with defaults
    op.add_column('user_preferences', sa.Column('s3_base_url', sa.String(length=500), nullable=True))
    op.execute("ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS allow_new_user_registration BOOLEAN NOT NULL DEFAULT TRUE")
    op.add_column('user_preferences', sa.Column('secret_key', sa.String(length=255), nullable=True))
    op.execute("ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS session_cookie_name VARCHAR(100) NOT NULL DEFAULT 'captains_log_session'")
    op.execute("ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS session_max_age INTEGER NOT NULL DEFAULT 2592000")
    op.add_column('user_preferences', sa.Column('google_oauth_client_id', sa.String(length=255), nullable=True))
    op.add_column('user_preferences', sa.Column('google_oauth_client_secret', sa.String(length=255), nullable=True))
    op.add_column('user_preferences', sa.Column('facebook_oauth_client_id', sa.String(length=255), nullable=True))
    op.add_column('user_preferences', sa.Column('facebook_oauth_client_secret', sa.String(length=255), nullable=True))
    op.add_column('user_preferences', sa.Column('github_oauth_client_id', sa.String(length=255), nullable=True))
    op.add_column('user_preferences', sa.Column('github_oauth_client_secret', sa.String(length=255), nullable=True))

    # Add User fields - FastAPI Users requires these to be NOT NULL, but we need to handle existing users
    # First add as nullable, set defaults for existing rows, then make NOT NULL
    op.add_column('users', sa.Column('hashed_password', sa.String(length=1024), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))

    # Update existing users with default values
    # Default password hash for "password" (bcrypt)
    op.execute("UPDATE users SET hashed_password = '$2b$12$LQv3c1yqBWVHxkd0LHAkCOYz6TtxMQJqhN8/LewY5GyYNkYVzE6Ge' WHERE hashed_password IS NULL")
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")
    op.execute("UPDATE users SET is_superuser = FALSE WHERE is_superuser IS NULL")
    op.execute("UPDATE users SET is_verified = TRUE WHERE is_verified IS NULL")

    # Now make columns NOT NULL
    op.alter_column('users', 'hashed_password', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)
    op.alter_column('users', 'is_superuser', nullable=False)
    op.alter_column('users', 'is_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_superuser')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'hashed_password')
    op.drop_column('user_preferences', 'github_oauth_client_secret')
    op.drop_column('user_preferences', 'github_oauth_client_id')
    op.drop_column('user_preferences', 'facebook_oauth_client_secret')
    op.drop_column('user_preferences', 'facebook_oauth_client_id')
    op.drop_column('user_preferences', 'google_oauth_client_secret')
    op.drop_column('user_preferences', 'google_oauth_client_id')
    op.drop_column('user_preferences', 'session_max_age')
    op.drop_column('user_preferences', 'session_cookie_name')
    op.drop_column('user_preferences', 'secret_key')
    op.drop_column('user_preferences', 'allow_new_user_registration')
    op.drop_column('user_preferences', 's3_base_url')
    # ### end Alembic commands ###
