"""Initial migration with pgvector

Revision ID: dcea7745b69b
Revises: 
Create Date: 2025-11-19 04:04:19.166796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'dcea7745b69b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create pgvector extension if not exists
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('audio_s3_key', sa.String(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'TRANSCRIBING', 'VECTORIZING', 'SUMMARIZING', 'COMPLETED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_entries')
    # ### end Alembic commands ###
